"use Client"
import type { Metadata } from "next";
import "./globals.css";

import { AppContext  } from "./components/AppContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-black">
      <AppContext>
        {children}
       </AppContext>
      </body>
    </html>
  );
}
